// frontend/src/components/CustomCursor.tsx
import { useEffect, useRef } from 'react';
import './CustomCursor.css';

const interactive = [
  'a', 'button', '[role="button"]', '.cursor-pointer', '.skill-card',
  '.project-card', '.project-media', '.bio-card', '.exp-item',
  '.photo-card', '.theme-toggle-btn', '.tech-badge', 'label',
].join(',');
const textTargets = 'input, textarea, select, [contenteditable="true"]';

export default function CustomCursor() {
  const dotRef = useRef<HTMLDivElement>(null);
  const ringRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!window.matchMedia('(pointer: fine)').matches) return;
    let mouseX = -100, mouseY = -100, ringX = -100, ringY = -100;
    let hovering = false, clicking = false, visible = false, textTarget = false;
    let frame = 0;

    const onMove = (event: MouseEvent) => {
      mouseX = event.clientX;
      mouseY = event.clientY;
      if (!visible) { visible = true; ringX = mouseX; ringY = mouseY; }
      const target = event.target as HTMLElement | null;
      textTarget = Boolean(target?.closest(textTargets));
      hovering = !textTarget && Boolean(target?.closest(interactive));
    };
    const onDown = () => { clicking = true; };
    const onUp = () => { clicking = false; };
    const onLeave = () => { visible = false; };
    const onEnter = () => { visible = true; };

    const render = () => {
      ringX += (mouseX - ringX) * 0.18;
      ringY += (mouseY - ringY) * 0.18;
      const dot = dotRef.current;
      const ring = ringRef.current;
      if (dot && ring) {
        dot.style.opacity = ring.style.opacity = visible && !textTarget ? '1' : '0';
        dot.style.transform = 'translate3d(' + mouseX + 'px,' + mouseY + 'px,0) translate(-50%,-50%) scale(' + (hovering ? 0.65 : clicking ? 0.8 : 1) + ')';
        ring.style.transform = 'translate3d(' + ringX + 'px,' + ringY + 'px,0) translate(-50%,-50%) scale(' + (clicking ? 0.75 : hovering ? 1.55 : 1) + ')';
        ring.classList.toggle('is-hovering', hovering);
        ring.classList.toggle('is-clicking', clicking);
      }
      frame = requestAnimationFrame(render);
    };

    window.addEventListener('mousemove', onMove, { passive: true });
    window.addEventListener('mousedown', onDown, { passive: true });
    window.addEventListener('mouseup', onUp, { passive: true });
    document.addEventListener('mouseleave', onLeave, { passive: true });
    document.addEventListener('mouseenter', onEnter, { passive: true });
    frame = requestAnimationFrame(render);
    return () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mousedown', onDown);
      window.removeEventListener('mouseup', onUp);
      document.removeEventListener('mouseleave', onLeave);
      document.removeEventListener('mouseenter', onEnter);
      cancelAnimationFrame(frame);
    };
  }, []);

  return <div className="custom-cursor-container" aria-hidden="true"><div ref={dotRef} className="cursor-dot" /><div ref={ringRef} className="cursor-ring" /></div>;
}

// frontend/src/components/CustomCursor.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

const dotRef = ref<HTMLDivElement | null>(null);
const ringRef = ref<HTMLDivElement | null>(null);

let mouseX = -100;
let mouseY = -100;
let ringX = -100;
let ringY = -100;

let isHovering = false;
let isClicking = false;
let isVisible = false;
let isTextTarget = false;
let animationFrameId: number | null = null;

const INTERACTIVE_SELECTORS = [
  'a',
  'button',
  '[role="button"]',
  '.cursor-pointer',
  '.skill-card',
  '.project-card',
  '.project-media',
  '.bio-card',
  '.exp-item',
  '.photo-card',
  '.theme-toggle-btn',
  '.tech-badge',
  'label'
].join(',');

const TEXT_SELECTORS = 'input, textarea, select, [contenteditable="true"]';

function onMouseMove(e: MouseEvent) {
  mouseX = e.clientX;
  mouseY = e.clientY;

  if (!isVisible) {
    isVisible = true;
    ringX = mouseX;
    ringY = mouseY;
  }

  const target = e.target as HTMLElement | null;
  if (target) {
    isTextTarget = Boolean(target.closest(TEXT_SELECTORS));
    isHovering = !isTextTarget && Boolean(target.closest(INTERACTIVE_SELECTORS));
  }
}

function onMouseDown() {
  isClicking = true;
}

function onMouseUp() {
  isClicking = false;
}

function onMouseLeave() {
  isVisible = false;
}

function onMouseEnter() {
  isVisible = true;
}

function render() {
  // Smooth lerp interpolation for natural trailing inertia
  const lerp = 0.18;
  ringX += (mouseX - ringX) * lerp;
  ringY += (mouseY - ringY) * lerp;

  if (dotRef.value && ringRef.value) {
    if (!isVisible || isTextTarget) {
      dotRef.value.style.opacity = '0';
      ringRef.value.style.opacity = '0';
    } else {
      dotRef.value.style.opacity = '1';
      ringRef.value.style.opacity = '1';

      // Pinpoint center precision dot
      const dotScale = isHovering ? 0.65 : isClicking ? 0.8 : 1;
      dotRef.value.style.transform = `translate3d(${mouseX}px, ${mouseY}px, 0) translate(-50%, -50%) scale(${dotScale})`;

      // Dynamic reactive follower ring
      const ringScale = isClicking ? 0.75 : isHovering ? 1.55 : 1;
      ringRef.value.style.transform = `translate3d(${ringX}px, ${ringY}px, 0) translate(-50%, -50%) scale(${ringScale})`;
    }

    if (isHovering) {
      ringRef.value.classList.add('is-hovering');
    } else {
      ringRef.value.classList.remove('is-hovering');
    }

    if (isClicking) {
      ringRef.value.classList.add('is-clicking');
    } else {
      ringRef.value.classList.remove('is-clicking');
    }
  }

  animationFrameId = requestAnimationFrame(render);
}

onMounted(() => {
  // Only enable on desktop/laptops with a mouse or trackpad
  if (window.matchMedia('(pointer: fine)').matches) {
    window.addEventListener('mousemove', onMouseMove, { passive: true });
    window.addEventListener('mousedown', onMouseDown, { passive: true });
    window.addEventListener('mouseup', onMouseUp, { passive: true });
    document.addEventListener('mouseleave', onMouseLeave, { passive: true });
    document.addEventListener('mouseenter', onMouseEnter, { passive: true });

    animationFrameId = requestAnimationFrame(render);
  }
});

onUnmounted(() => {
  window.removeEventListener('mousemove', onMouseMove);
  window.removeEventListener('mousedown', onMouseDown);
  window.removeEventListener('mouseup', onMouseUp);
  document.removeEventListener('mouseleave', onMouseLeave);
  document.removeEventListener('mouseenter', onMouseEnter);

  if (animationFrameId !== null) {
    cancelAnimationFrame(animationFrameId);
  }
});
</script>

<template>
  <div class="custom-cursor-container" aria-hidden="true">
    <!-- Center Precision Dot -->
    <div ref="dotRef" class="cursor-dot"></div>

    <!-- Smooth Follower Ring -->
    <div ref="ringRef" class="cursor-ring"></div>
  </div>
</template>

<style scoped>
.custom-cursor-container {
  pointer-events: none;
  position: fixed;
  inset: 0;
  z-index: 9999999;
  overflow: hidden;
}

@media (pointer: coarse) {
  .custom-cursor-container {
    display: none !important;
  }
}

.cursor-dot {
  position: fixed;
  top: 0;
  left: 0;
  width: 6px;
  height: 6px;
  border-radius: 9999px;
  background: var(--color-accent, #3A5A6B);
  box-shadow: 0 0 10px rgba(58, 90, 107, 0.85);
  pointer-events: none;
  opacity: 0;
  transition: opacity 0.2s ease;
  will-change: transform, opacity;
}

.cursor-ring {
  position: fixed;
  top: 0;
  left: 0;
  width: 32px;
  height: 32px;
  border-radius: 9999px;
  border: 1.5px solid rgba(58, 90, 107, 0.45);
  background: rgba(58, 90, 107, 0.02);
  pointer-events: none;
  opacity: 0;
  transition: opacity 0.25s ease, border-color 0.25s ease, background-color 0.25s ease, box-shadow 0.25s ease;
  will-change: transform, opacity;
}

.cursor-ring.is-hovering {
  border-color: rgba(58, 90, 107, 0.9);
  background: rgba(58, 90, 107, 0.12);
  box-shadow: 0 0 22px rgba(58, 90, 107, 0.32), inset 0 0 10px rgba(58, 90, 107, 0.1);
}

.cursor-ring.is-clicking {
  border-color: var(--color-accent, #3A5A6B);
  background: rgba(58, 90, 107, 0.25);
  box-shadow: 0 0 24px rgba(58, 90, 107, 0.5);
}
</style>
